language: node_js
node_js:
  - "4.1"
install:
  - npm install
  - bower install
script:
  - gulp dist
after_success:
  - touch dist/.surgeignore && echo '!bower_components/' > dist/.surgeignore
deploy:
  on: master
  skip_cleanup: true
  provider: surge
  project: dist/
  domain: apiweasel.themihel.me
