language: node_js
branches:
  only:
    - master
node_js:
  - "4.1"
install:
  - npm install
  - bower install
script:
  - gulp dist
after_success:
  - touch dist/.surgeignore && echo '!bower_components/' > dist/.surgeignore
  - surge --project ./dist --domain apiweasel.themihel.me
